namespace ForgeAssistant {
    public static class ItemParser {
        public static string GetItemNameFromType(int type, string MapName) {
            //Universal Codes
            switch (type) {
                case 0x0000: return "Assault Rifle";
                case 0x0100: return "DMR";
                case 0x0200: return "Grenade Launcher";
                case 0x0300: return "Magnum";
                case 0x0400: return "Rocket Launcher";
                case 0x0500: return "Shotgun";
                case 0x0600: return "Sniper Rifle";
                case 0x0700: return "Spartan Laser";
                case 0x0800: return "Frag Grenade";
                case 0x0900: return "Mounted Machinegun";
                case 0x0A00: return "Concussion Rifle";
                case 0x0B00: return "Energy Sword";
                case 0x0C00: return "Fuel Rod Gun";
                case 0x0D00: return "Gravity Hammer";
                case 0x0E00: return "Focus Rifle";
                case 0x0F00: return "Needle Rifle";
                case 0x1000: return "Needler";
                case 0x1100: return "Plasma Launcher";
                case 0x1200: return "Plasma Pistol";
                case 0x1300: return "Plasma Repeater";
                case 0x1400: return "Plasma Rifle";
                case 0x1500: return "Spiker";
                case 0x1600: return "Plasma Grenade";
                case 0x1700: return "Plasma Turret";
                case 0x1800: return "Active Camouflage";
                case 0x1900: return "Armor Lock";
                case 0x1A00: return "Drop Shield";
                case 0x1B00: return "Evade";
                case 0x1C00: return "Hologram";
                case 0x1D00: return "Jet Pack";
                case 0x1E00: return "Sprint";
            }

            if (MapName == "forge_halo") {
                switch (type) {
                    case 0x1F00: return "Banshee";
                    case 0x2000: return "Falcon";
                    case 0x2100: return "Ghost";
                    case 0x2200: return "Mongoose";
                    case 0x2300: return "Revenant";
                    case 0x2400: return "Scorpion";
                    case 0x2500: return "Shade Turret";
                    case 0x2600: return "Warthog, Default";
                    case 0x2601: return "Warthog, Gauss";
                    case 0x2602: return "Warthog, Rocket";
                    case 0x2700: return "Wraith";
                    case 0x2800: return "Fusion Coil";
                    case 0x2801: return "Landmine";
                    case 0x2802: return "Plasma Battery";
                    case 0x2803: return "Propane Tank";
                    case 0x2900: return "Health Station";
                    case 0x2A00: return "Camo Powerup";
                    case 0x2A01: return "Overshield";
                    case 0x2A02: return "Custom Powerup";
                    case 0x2B00: return "Cannon, Man";
                    case 0x2B01: return "Cannon, Man, Heavy";
                    case 0x2B02: return "Cannon, Man, Light";
                    case 0x2B03: return "Cannon, Vehicle";
                    case 0x2B04: return "Gravity Lift";
                    case 0x2C00: return "One Way Shield 2";
                    case 0x2D00: return "One Way Shield 3";
                    case 0x2E00: return "One Way Shield 4";
                    case 0x2F00: return "FX:Colorblind";
                    case 0x2F01: return "FX:Next Gen";
                    case 0x2F02: return "FX:Juicy";
                    case 0x2F03: return "FX:Nova";
                    case 0x2F04: return "FX:Olde Timey";
                    case 0x2F05: return "FX:Pen And Ink";
                    case 0x2F06: return "FX:Purple";
                    case 0x2F07: return "FX:Green";
                    case 0x2F08: return "FX:Orange";
                    case 0x3000: return "Shield Door, Small";
                    case 0x3100: return "Shield Door, Medium";
                    case 0x3200: return "Shield Door, Large";
                    case 0x3300: return "Receiver Node";
                    case 0x3301: return "Sender Node";
                    case 0x3302: return "Two-Way Node";
                    case 0x3400: return "Die";
                    case 0x3401: return "Golf Ball";
                    case 0x3402: return "Golf Club";
                    case 0x3403: return "Kill Ball";
                    case 0x3404: return "Soccer Ball";
                    case 0x3405: return "Tin Cup";
                    case 0x3500: return "Light, Red";
                    case 0x3501: return "Light, Blue";
                    case 0x3502: return "Light, Green";
                    case 0x3503: return "Light, Orange";
                    case 0x3504: return "Light, Purple";
                    case 0x3505: return "Light, Yellow";
                    case 0x3506: return "Light, White";
                    case 0x3507: return "Light, Red, Flashing";
                    case 0x3508: return "Light, Yellow, Flashing";
                    case 0x3600: return "Initial Spawn";
                    case 0x3700: return "Respawn Point";
                    case 0x3800: return "Initial Loadout Camera";
                    case 0x3900: return "Respawn Zone";
                    case 0x3A00: return "Respawn Zone, Weak";
                    case 0x3B00: return "Respawn Zone, Anti";
                    case 0x3C00: return "Safe Boundary";
                    case 0x3C01: return "Soft Safe Boundary";
                    case 0x3D00: return "Kill Boundary";
                    case 0x3D01: return "Soft Kill Boundary";
                    case 0x3E00: return "Flag Stand";
                    case 0x3F00: return "Capture Plate";
                    case 0x4000: return "Hill Marker";
                    case 0x4100: return "Barricade, Small";
                    case 0x4101: return "Barricade, Large";
                    case 0x4102: return "Covenant Barrier";
                    case 0x4103: return "Portable Shield";
                    case 0x4200: return "Camping Stool";
                    case 0x4300: return "Crate, Heavy Duty";
                    case 0x4301: return "Crate, Heavy, Small";
                    case 0x4302: return "Covenant Crate";
                    case 0x4303: return "Crate, Half Open";
                    case 0x4400: return "Sandbag Wall";
                    case 0x4401: return "Sandbag, Turret Wall";
                    case 0x4402: return "Sandbag Corner, 45";
                    case 0x4403: return "Sandbag Corner, 90";
                    case 0x4404: return "Sandbag Endcap";
                    case 0x4500: return "Street Cone";
                    case 0x4600: return "Block, 1x1";
                    case 0x4601: return "Block, 1x1, Flat";
                    case 0x4602: return "Block, 1x1, Short";
                    case 0x4603: return "Block, 1x1, Tall";
                    case 0x4604: return "Block, 1x1, Tall And Thin";
                    case 0x4605: return "Block, 1x2";
                    case 0x4606: return "Block, 1x4";
                    case 0x4607: return "Block, 2x1, Flat";
                    case 0x4608: return "Block, 2x2";
                    case 0x4609: return "Block, 2x2, Flat";
                    case 0x460A: return "Block, 2x2, Short";
                    case 0x460B: return "Block, 2x2, Tall";
                    case 0x460C: return "Block, 2x3";
                    case 0x460D: return "Block, 2x4";
                    case 0x460E: return "Block, 3x1, Flat";
                    case 0x460F: return "Block, 3x3";
                    case 0x4610: return "Block, 3x3, Flat";
                    case 0x4611: return "Block, 3x3, Short";
                    case 0x4612: return "Block, 3x3, Tall";
                    case 0x4613: return "Block, 3x4";
                    case 0x4614: return "Block, 4x4";
                    case 0x4615: return "Block, 4x4, Flat";
                    case 0x4616: return "Block, 4x4, Short";
                    case 0x4617: return "Block, 4x4, Tall";
                    case 0x4618: return "Block, 5x1, Short";
                    case 0x4619: return "Block, 5x5, Flat";
                    case 0x4700: return "Bridge, Small";
                    case 0x4701: return "Bridge, Medium";
                    case 0x4702: return "Bridge, Large";
                    case 0x4703: return "Bridge, XLarge";
                    case 0x4704: return "Bridge, Diagonal";
                    case 0x4705: return "Bridge, Diag, Small";
                    case 0x4706: return "Dish";
                    case 0x4707: return "Dish, Open";
                    case 0x4708: return "Corner, 45 Degrees";
                    case 0x4709: return "Corner, 2x2";
                    case 0x470A: return "Corner, 4x4";
                    case 0x470B: return "Landing Pad";
                    case 0x470C: return "Platform, Ramped";
                    case 0x470D: return "Platform, Large";
                    case 0x470E: return "Platform, XL";
                    case 0x470F: return "Platform, XXL";
                    case 0x4710: return "Platform, Y";
                    case 0x4711: return "Platform, Y, Large";
                    case 0x4712: return "Sniper Nest";
                    case 0x4713: return "Staircase";
                    case 0x4714: return "Walkway, Large";
                    case 0x4800: return "Bunker, Small";
                    case 0x4801: return "Bunker, Small, Covered";
                    case 0x4802: return "Bunker, Box";
                    case 0x4803: return "Bunker, Round";
                    case 0x4804: return "Bunker, Ramp";
                    case 0x4805: return "Pyramid";
                    case 0x4806: return "Tower, 2 Story";
                    case 0x4807: return "Tower, 3 Story";
                    case 0x4808: return "Tower, Tall";
                    case 0x4809: return "Room, Double";
                    case 0x480A: return "Room, Triple";
                    case 0x4900: return "Antenna, Small";
                    case 0x4901: return "Antenna, Satellite";
                    case 0x4902: return "Brace";
                    case 0x4903: return "Brace, Large";
                    case 0x4904: return "Brace, Tunnel";
                    case 0x4905: return "Column";
                    case 0x4906: return "Cover";
                    case 0x4907: return "Cover, Crenellation";
                    case 0x4908: return "Cover, Glass";
                    case 0x4909: return "Glass Sail";
                    case 0x490A: return "Railing, Small";
                    case 0x490B: return "Railing, Medium";
                    case 0x490C: return "Railing, Long";
                    case 0x490D: return "Teleporter Frame";
                    case 0x490E: return "Strut";
                    case 0x490F: return "Large Walkway Cover";
                    case 0x4A00: return "Door";
                    case 0x4A01: return "Door, Double";
                    case 0x4A02: return "Window";
                    case 0x4A03: return "Window, Double";
                    case 0x4A04: return "Wall";
                    case 0x4A05: return "Wall, Double";
                    case 0x4A06: return "Wall, Corner";
                    case 0x4A07: return "Wall, Curved";
                    case 0x4A08: return "Wall, Coliseum";
                    case 0x4A09: return "Window, Colesium";
                    case 0x4A0A: return "Tunnel, Short";
                    case 0x4A0B: return "Tunnel, Long";
                    case 0x4B00: return "Bank, 1x1";
                    case 0x4B01: return "Bank, 1x2";
                    case 0x4B02: return "Bank, 2x1";
                    case 0x4B03: return "Bank, 2x2";
                    case 0x4B04: return "Ramp, 1x2";
                    case 0x4B05: return "Ramp, 1x2, Shallow";
                    case 0x4B06: return "Ramp, 2x2";
                    case 0x4B07: return "Ramp, 2x2, Steep";
                    case 0x4B08: return "Ramp, Circular, Small";
                    case 0x4B09: return "Ramp, Circular, Large";
                    case 0x4B0A: return "Ramp, Bridge, Small";
                    case 0x4B0B: return "Ramp, Bridge, Medium";
                    case 0x4B0C: return "Ramp, Bridge, Large";
                    case 0x4B0D: return "Ramp, XL";
                    case 0x4B0E: return "Ramp, Stunt";
                    case 0x4C00: return "Rock, Small";
                    case 0x4C01: return "Rock, Flat";
                    case 0x4C02: return "Rock, Medium 1";
                    case 0x4C03: return "Rock, Medium 2";
                    case 0x4C04: return "Rock, Spire 1";
                    case 0x4C05: return "Rock, Spire 2";
                    case 0x4C06: return "Rock, Seastack";
                    case 0x4C07: return "Rock, Arch";
                    case 0x4D00: return "Grid";
                    case 0x5900: return "Falcon, Nose Gun";
                    case 0x5901: return "Falcon, Grenadier";
                    case 0x5902: return "Falcon, Transport";
                    case 0x5A00: return "Warthog, Transport";
                    case 0x5B00: return "Sabre";
                    case 0x5C00: return "Seraph";
                    case 0x5D00: return "Cart, Electric";
                    case 0x5E00: return "Forklift";
                    case 0x5F00: return "Pickup";
                    case 0x6000: return "Truck Cab";
                    case 0x6100: return "Van, Oni";
                    case 0x6200: return "Shade, Fuel Rod";
                    case 0x6300: return "Cannon, Man";
                    case 0x6301: return "Cannon, Man, Heavy";
                    case 0x6302: return "Cannon, Man, Light";
                    case 0x6303: return "Gravity Lift, Forerunner";
                    case 0x6304: return "Gravity Lift, Tall, Forerunner";
                    case 0x6305: return "Cannon, Man, Human";
                    case 0x6400: return "One Way Shield 1";
                    case 0x6500: return "One Way Shield 5";
                    case 0x6600: return "Shield Wall, Small";
                    case 0x6700: return "Shield Wall, Medium";
                    case 0x6800: return "Shield Wall, Large";
                    case 0x6900: return "Shield Wall, X-Large";
                    case 0x6A00: return "One Way Shield 2";
                    case 0x6B00: return "One Way Shield 3";
                    case 0x6C00: return "One Way Shield 4";
                    case 0x6D00: return "Shield Door, Small";
                    case 0x6E00: return "Shield Door, Small 1";
                    case 0x6F00: return "Shield Door, Large";
                    case 0x7000: return "Shield Door, Large 1";
                    case 0x7100: return "Ammo Cabinet";
                    case 0x7200: return "Spnkr Ammo";
                    case 0x7300: return "Sniper Ammo";
                    case 0x7400: return "Jersey Barrier";
                    case 0x7401: return "Jersey Barrier, Short";
                    case 0x7402: return "Heavy Barrier";
                    case 0x7500: return "Small, Closed";
                    case 0x7501: return "Crate, Metal, Multi";
                    case 0x7502: return "Crate, Metal, Single";
                    case 0x7503: return "Crate, Fully Open";
                    case 0x7504: return "Crate, Forerunner, Small";
                    case 0x7505: return "Crate, Forerunner, Large";
                    case 0x7600: return "Pallet";
                    case 0x7601: return "Pallet, Large";
                    case 0x7602: return "Pallet, Metal";
                    case 0x7700: return "Driftwood 1";
                    case 0x7701: return "Driftwood 2";
                    case 0x7702: return "Driftwood 3";
                    case 0x7800: return "Phantom";
                    case 0x7801: return "Spirit";
                    case 0x7802: return "Pelican";
                    case 0x7803: return "Drop Pod, Elite";
                    case 0x7804: return "Anti Air Gun";
                    case 0x7900: return "Cargo Truck, Destroyed";
                    case 0x7901: return "Falcon, Destroyed";
                    case 0x7902: return "Warthog, Destroyed";
                    case 0x7A00: return "Folding Chair";
                    case 0x7B00: return "Dumpster";
                    case 0x7C00: return "Dumpster, Tall";
                    case 0x7D00: return "Equipment Case";
                    case 0x7E00: return "Monitor";
                    case 0x7F00: return "Plasma Storage";
                    case 0x8000: return "Camping Stool, Covenant";
                    case 0x8100: return "Covenant Antenna";
                    case 0x8200: return "Fuel Storage";
                    case 0x8300: return "Engine Cart";
                    case 0x8400: return "Missile Cart";
                    case 0x8500: return "Bridge";
                    case 0x8501: return "Platform, Covenant";
                    case 0x8502: return "Catwalk, Straight";
                    case 0x8503: return "Catwalk, Short";
                    case 0x8504: return "Catwalk, Bend, Left";
                    case 0x8505: return "Catwalk, Bend, Right";
                    case 0x8506: return "Catwalk, Angled";
                    case 0x8507: return "Catwalk, Large";
                    case 0x8600: return "Bunker, Overlook";
                    case 0x8601: return "Gunners Nest";
                    case 0x8700: return "Cover, Small";
                    case 0x8701: return "Block, Large";
                    case 0x8702: return "Blocker, Hallway";
                    case 0x8703: return "Column, Stone";
                    case 0x8704: return "Tombstone";
                    case 0x8705: return "Cover, Large, Stone";
                    case 0x8706: return "Cover, Large";
                    case 0x8707: return "Walkway Cover";
                    case 0x8708: return "Walkway Cover, Short";
                    case 0x8709: return "Cover, Large, Human";
                    case 0x870A: return "I-Beam";
                    case 0x8800: return "Wall";
                    case 0x8801: return "Door";
                    case 0x8802: return "Door, Human";
                    case 0x8803: return "Door A, Forerunner";
                    case 0x8804: return "Door B, Forerunner";
                    case 0x8805: return "Door C, Forerunner";
                    case 0x8806: return "Door D, Forerunner";
                    case 0x8807: return "Door E, Forerunner";
                    case 0x8808: return "Door F, Forerunner";
                    case 0x8809: return "Door G, Forerunner";
                    case 0x880A: return "Door H, Forerunner";
                    case 0x880B: return "Wall, Small, Forerunner";
                    case 0x880C: return "Wall, Large, Forerunner";
                    case 0x8900: return "Rock, Spire 3";
                    case 0x8901: return "Tree, Dead";
                    case 0x8D00: return "Target Designator";
                }
            }

            return "Unknown";
        }
    }
}
