import json
import sys
import os
import re
from pathlib import Path

def parse_palette_json(json_path):
    """
    Parse a JSON file exported from Assembly.exe and return a palette dictionary
    in the format expected by forge.py (TwoWayDict format).
    """
    with open(json_path, 'r') as f:
        tags = json.load(f)
    
    id_map = {}
    
    i = 0
    for category in tags['Data']['Map Variant Palettes']:
        for item in category['Entries']:
            entry_name = item['Name']
            variants = item['Variants']
            do_inc = len(variants)
            for var in variants:
                display_name = var['Display Name']
                # Use display name if it exists, otherwise use entry name
                id_map[i] = entry_name if display_name == "" else display_name
                if do_inc: 
                    i += 1
            # Move to next category (increment by 256)
            i = (i + (1 << 8)) & 0xFF00
    
    return id_map

def format_as_twowaydict(id_map):
    """
    Format the palette dictionary as Python code for TwoWayDict initialization.
    """
    items = sorted(id_map.items())
    result = "TwoWayDict({"
    result += ", ".join([f"{k}: '{v}'" for k, v in items])
    result += "})"
    return result

def find_forge_py():
    """
    Try to find forge.py in the expected location.
    """
    # Get the directory of this script
    script_dir = Path(__file__).parent
    
    # Try common locations
    possible_paths = [
        script_dir.parent / "Blender (Download a Release, Not Me!)" / "forge.py",
        script_dir.parent / "forge.py",
        Path("forge.py"),
    ]
    
    for path in possible_paths:
        if path.exists():
            return path
    
    return None

def add_map_to_forge_py(forge_py_path, map_name, twowaydict_str):
    """
    Automatically add the new map to forge.py.
    Returns True if successful, False otherwise.
    """
    try:
        # Read the file
        with open(forge_py_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Find the map_object_types dictionary
        pattern = r'(map_object_types\s*=\s*\{)'
        match = re.search(pattern, content)
        
        if not match:
            print("Error: Could not find map_object_types dictionary in forge.py")
            return False
        
        # Find the closing brace of the dictionary
        dict_start = match.end()
        brace_count = 1
        pos = dict_start
        
        while pos < len(content) and brace_count > 0:
            if content[pos] == '{':
                brace_count += 1
            elif content[pos] == '}':
                brace_count -= 1
            pos += 1
        
        if brace_count != 0:
            print("Error: Could not parse map_object_types dictionary structure")
            return False
        
        # Insert the new map entry before the closing brace
        insert_pos = pos - 1
        
        # Find the last comma before the closing brace
        last_content = content[dict_start:insert_pos].rstrip()
        if last_content and not last_content.endswith(','):
            # Add comma after the last entry
            new_entry = f',\n    "{map_name}"       : {twowaydict_str},'
        else:
            new_entry = f'\n    "{map_name}"       : {twowaydict_str},'
        
        # Create the new content
        new_content = content[:insert_pos] + new_entry + '\n' + content[insert_pos:]
        
        # Create backup
        backup_path = forge_py_path.with_suffix('.py.backup')
        with open(backup_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        # Write the modified content
        with open(forge_py_path, 'w', encoding='utf-8') as f:
            f.write(new_content)
        
        print(f"✓ Backup created: {backup_path}")
        print(f"✓ Map '{map_name}' added to forge.py")
        return True
        
    except Exception as e:
        print(f"Error modifying forge.py: {e}")
        return False

def save_to_file(output_path, map_name, twowaydict_str):
    """
    Save the map data to a standalone file.
    """
    content = f'''# Map palette for: {map_name}
# Generated by parse_palette.py
# Copy this line into forge.py's map_object_types dictionary:

    "{map_name}"       : {twowaydict_str},

'''
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"✓ Saved to: {output_path}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python parse_palette.py <path_to_json_file> [map_name] [--auto|--save]")
        print("\nSimple usage (prints output to copy/paste):")
        print('  python parse_palette.py headlong.json')
        print('  python parse_palette.py headlong.json "Headlong"')
        print("\nAdvanced usage:")
        print('  python parse_palette.py headlong.json "Headlong" --auto   (auto-add to forge.py)')
        print('  python parse_palette.py headlong.json "Headlong" --save   (save to file)')
        print("\nOptions:")
        print("  --auto    Automatically add to forge.py (creates backup)")
        print("  --save    Save to a .py file for manual copying")
        sys.exit(1)
    
    json_path = sys.argv[1]
    
    # Extract map name from filename if not provided
    if len(sys.argv) > 2 and not sys.argv[2].startswith('--'):
        map_name = sys.argv[2]
        mode = sys.argv[3] if len(sys.argv) > 3 else None
    else:
        # Try to guess map name from filename
        map_name = Path(json_path).stem.replace('_', ' ').title()
        mode = sys.argv[2] if len(sys.argv) > 2 else None
    
    try:
        # Parse the JSON
        id_map = parse_palette_json(json_path)
        twowaydict_str = format_as_twowaydict(id_map)
        
        print(f"\n{'='*60}")
        print(f"Parsed palette for: {map_name}")
        print(f"Objects found: {len(id_map)}")
        print(f"{'='*60}\n")
        
        # Handle different modes
        if mode == '--auto':
            # Try to find and modify forge.py automatically
            forge_py_path = find_forge_py()
            
            if forge_py_path:
                print(f"Found forge.py at: {forge_py_path}\n")
                
                # Ask for confirmation
                response = input(f"Add '{map_name}' to forge.py? (y/n): ").lower()
                
                if response == 'y':
                    if add_map_to_forge_py(forge_py_path, map_name, twowaydict_str):
                        print("\n✓ Success! Map added to forge.py")
                        print("  A backup was created with .backup extension")
                        print("  You can now use this map in Blender!")
                    else:
                        print("\n✗ Failed to modify forge.py")
                        print("  See error above for details")
                else:
                    print("\nCancelled. No changes made.")
            else:
                print("✗ Could not find forge.py automatically")
                print("  Try using --save to create a file you can copy manually")
        
        elif mode == '--save':
            # Save to a file
            output_name = map_name.lower().replace(' ', '_')
            output_path = Path(f"{output_name}_palette.py")
            save_to_file(output_path, map_name, twowaydict_str)
            print(f"\nTo use this map:")
            print(f"  1. Open forge.py")
            print(f"  2. Find the map_object_types dictionary")
            print(f"  3. Copy the line from {output_path}")
            print(f"  4. Paste it into the dictionary")
        
        else:
            # Just print the output
            print("Generated TwoWayDict:")
            print("-" * 60)
            print(f'    "{map_name}"       : {twowaydict_str},')
            print("-" * 60)
            print("\nRaw data (for debugging):")
            print(f"  Total objects: {len(id_map)}")
            print(f"  First object: {list(id_map.items())[0] if id_map else 'None'}")
            print(f"  Last object: {list(id_map.items())[-1] if id_map else 'None'}")
            print("\nNext steps:")
            print("  1. Copy the line above (including quotes and comma)")
            print("  2. Open forge.py and find map_object_types = {")
            print("  3. Paste the line before the closing }")
            print("\nOr run again with --auto to add automatically:")
            print(f'  python parse_palette.py "{json_path}" "{map_name}" --auto')
        
    except FileNotFoundError:
        print(f"✗ Error: File not found: {json_path}")
        sys.exit(1)
    except KeyError as e:
        print(f"✗ Error: Invalid JSON structure. Missing key: {e}")
        print("  Make sure you exported the palette data from Assembly.exe correctly")
        sys.exit(1)
    except Exception as e:
        print(f"✗ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)